{"level":"error","message":"TypeError: PvRecorder.get_avaliable_devices is not a function\n    at new AudioWorker (file:///Users/yan_lobau/git/voice-assistant-poc/dist/infrastructure/input/audio/picovoice/AudioWorker.js:24:50)\n    at VoiceInput.recordMic (file:///Users/yan_lobau/git/voice-assistant-poc/dist/infrastructure/input/VoiceInput.js:23:27)\n    at file:///Users/yan_lobau/git/voice-assistant-poc/dist/infrastructure/input/VoiceInput.js:16:25\n    at new Promise (<anonymous>)\n    at VoiceInput.input (file:///Users/yan_lobau/git/voice-assistant-poc/dist/infrastructure/input/VoiceInput.js:15:16)\n    at Conversation.runLoop (file:///Users/yan_lobau/git/voice-assistant-poc/dist/core/Conversation.js:20:14)\n    at Conversation.start (file:///Users/yan_lobau/git/voice-assistant-poc/dist/core/Conversation.js:62:21)\n    at file:///Users/yan_lobau/git/voice-assistant-poc/dist/index.js:123:24"}
{"level":"error","message":"\u001b[31mУпс... Адбылася нечаканая памылка. Паспрабуйце каліласка яшчэ раз.\u001b[39m"}
{"level":"error"}
{"error":{"level":"error"},"level":"error","message":"Error initializing conversation"}
{"level":"error","message":"TypeError: this.recorder.get_avaliable_devices is not a function\n    at new AudioWorker (file:///Users/yan_lobau/git/voice-assistant-poc/dist/infrastructure/input/audio/picovoice/AudioWorker.js:25:53)\n    at VoiceInput.recordMic (file:///Users/yan_lobau/git/voice-assistant-poc/dist/infrastructure/input/VoiceInput.js:23:27)\n    at file:///Users/yan_lobau/git/voice-assistant-poc/dist/infrastructure/input/VoiceInput.js:16:25\n    at new Promise (<anonymous>)\n    at VoiceInput.input (file:///Users/yan_lobau/git/voice-assistant-poc/dist/infrastructure/input/VoiceInput.js:15:16)\n    at Conversation.runLoop (file:///Users/yan_lobau/git/voice-assistant-poc/dist/core/Conversation.js:20:14)\n    at Conversation.start (file:///Users/yan_lobau/git/voice-assistant-poc/dist/core/Conversation.js:62:21)\n    at file:///Users/yan_lobau/git/voice-assistant-poc/dist/index.js:123:24"}
{"level":"error","message":"\u001b[31mУпс... Адбылася нечаканая памылка. Паспрабуйце каліласка яшчэ раз.\u001b[39m"}
{"level":"error"}
{"error":{"level":"error"},"level":"error","message":"Error initializing conversation"}
{"level":"error","message":"Error executing arecord: Command failed: arecord -l\n/bin/sh: arecord: command not found\n"}
{"level":"error","message":"Unhandled Rejection at Promise","promise":{},"reason":"Error executing arecord -l: Command failed: arecord -l\n/bin/sh: arecord: command not found\n"}
{"level":"error","message":"Unhandled Rejection at Promise","promise":{},"reason":"Error executing arecord -l: Command failed: arecord -l\n/bin/sh: arecord: command not found\n"}
{"level":"error","message":"Error reading capture device index. Using default.\nError: Error executing arecord -l: Command failed: arecord -l\n/bin/sh: arecord: command not found\n"}
